# -*- coding: utf-8 -*-
"""customer_churn_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQZOCQd6elMuxW6JQNRok9Bc_XuqHGzd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/data/customer-churn-data.csv")

df.head(10)

df.isnull()

df.isnull().sum()

df.info()

df.describe()

# Remove blank spaces and convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Drop rows with missing TotalCharges
df = df.dropna(subset=['TotalCharges'])

# Convert 'Churn' to binary 1/0
df.loc[:, 'Churn_Encoded'] = df['Churn'].apply(lambda x: 1 if x=='Yes' else 0)

df

plt.figure(figsize=(6,6))
df['Churn'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Overall Churn Rate")
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(data=df, x='tenure', hue='Churn', kde=True, multiple='stack')
plt.title("Customer Tenure vs Churn")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Contract', hue='Churn')
plt.title("Churn by Contract Type")
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(data=df, x='Churn', y='MonthlyCharges')
plt.title("Monthly Charges Impact on Churn")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='PaymentMethod', hue='Churn')
plt.xticks(rotation=45)
plt.title("Payment Method vs Churn")
plt.show()

sns.countplot(x='Churn', data=df)

plt.figure(figsize=(12,8))
numeric_df = df.select_dtypes(include=['float64','int64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap (Numeric Columns Only)")
plt.show()

